spring:
  application:
    name: badasign

server:
  port: 58081

yousign:
  api:
    base-url: https://api.yousign.app/v3
    api-key: ${YOUSIGN_API_KEY:epx9QgykeB8kWTL6BIugAzTedB88cmQ3}
    
logging:
  level:
    fr.jixter.badasign: DEBUG
    root: INFO